// <auto-generated />
namespace Resume.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WhatNow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WhatNow));
        
        string IMigrationMetadata.Id
        {
            get { return "201509130336359_WhatNow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
